dist: trusty
language: cpp
compiler:
  - gcc
  - clang

before_install:
# C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-8; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90; fi
  # clang
  - deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main
  - deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main
  - apt-get install clang-8 lldb-8 lld-8

  # cppcheck
  - sudo apt-get install -qq cppcheck

script:
  - cmake --version
  - mkdir build; cd build; cmake -DOT_SANITIZE=OFF -DJAVA=OFF -DOT_STORAGE_SQLITE=ON .. -DOT_BUNDLED_PROTOBUF=OFF -DOT_BUNDLED_SODIUM=OFF  -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DOT_BUNDLED_OPENTXS_PROTO=OFF -DOT_BUNDLED_SSL=OFF -DOT_BUNDLED_SECP256K1=OFF -DOT_BUNDLED_LMDB=OFF -DOT_BUNDLED_SQLITE=OFF -DOT_BUNDLED_LIBZMQ=OFF -DOT_STORAGE_FS=ON -DOT_WITH_QT=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DOT_CASH_USING_LUCRE=OFF
  - make -j5
  
  

