os: linux
dist: xenial
language: cpp
git:
  depth: 9999999
compiler:
  - gcc
  - clang
before_install:
# C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-8; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90; fi
  # clang
  

  # cppcheck
  - sudo apt-get install -qq cppcheck
  - sudo apt-get install libprotobuf-dev protobuf-compiler
  - sudo apt-get install libsodium-dev libssl-dev
  - sudo add-apt-repository -y ppa:tah83/secp256k1 && sudo apt-get update
  - sudo apt-get install libsecp256k1-dev libzmq-dev libsqlite3-dev
  - sudo apt-get install liblmdb-dev
  - sudo apt-get install libboost-dev libboost-filesystem-dev libboost-iostreams-dev
  - sudo apt-get install libgtest-dev
  #fix GTest, symlink libgtest.a and libgtest_main.a to /usr/lib folder
  - sudo apt-get install cmake && cmake --version # install cmake
  - cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib

script:
  - cmake --version
  #- git fetch --unshallow 
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build && cmake -DOT_SANITIZE=OFF -DJAVA=OFF -DOT_STORAGE_SQLITE=ON .. -DOT_BUNDLED_PROTOBUF=OFF -DOT_BUNDLED_SODIUM=OFF  -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DOT_BUNDLED_OPENTXS_PROTO=ON -DOT_BUNDLED_SSL=OFF -DOT_BUNDLED_SECP256K1=OFF -DOT_BUNDLED_LMDB=OFF -DOT_BUNDLED_SQLITE=OFF -DOT_BUNDLED_LIBZMQ=OFF -DOT_STORAGE_FS=ON -DOT_WITH_QT=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DOT_CASH_USING_LUCRE=OFF && make -j5
  
